### ISSUE TITLE
what is the use of that LiPo Fuel Gauge？

### ISSUE THREAD

**Issue by scarrrr316** [pauls-3d-things/arduino-esp-lipo-meter#1]
I have read the source code and I found that It just used to tell us the voltage of battery and the % charged .But I think those data can read from ina219 and calculate by arduino ,

**Comment by uvwxy** [comment]
The LiPo Fuel Gauge measures the relative state of charge of a battery using the impedance of the battery and some algorithmic magic.

If you know the capacity of the battery and the starting point you can track the charge level, yes, but not if you don't know both of these values.

**Comment by scarrrr316** [comment]
ok......
